### PR TITLE
DiME Documentation Consistency Update

### PR DESCRIPTION
**Pull request by zmalkmus**
There is a lot here. I have gone over it a couple times to make sure I did not miss anything, but with how much I converted over there are bound to be errors. 

I did not end up using the same auto-summary generator as AGVis and ANDES as it required setting up auto-summary for 3 different languages, which I am not even sure would be possible with sphinx, but proved too much of a headache when trying to implement it anyways. However, I emulated the style of the other API's documentation, within reason, through manually writing/updating the old files to work with reStructuredText. 

As well, I partially updated the README as well to be consistent with the other LTB READMEs, but I need some links that will be generated from the new documentation to finish it.

For reviewing, I would recommend building this documentation and comparing the previous version.

Let me know if there are any questions or changes.

### CODE REVIEW

**Review by jinningwang — COMMENTED** [review]
It looks good to me, thanks a lot for your hard work!

**Comment by jinningwang** [comment]
You can add a GitHub action to enable the ReadTheDocs build for a PR. In this way, you can see if the documentation is able to make successful.

**Comment by jinningwang** [comment]
For the link you said, I would assume you are referring to the documentation status badge. I can see that you've included it in the README.

**Comment by zmalkmus** [comment]
I am going to add links to certain sections of the documentation. I think it was the agvis documentation that does something similar.

**Pull request merged**
